// Generated by Supabase (generate_typescript_types) for project bvynhmxyvqkitwyndlyt.
// Regenerate after schema changes; do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      accounts: {
        Row: {
          created_at: string
          email: string | null
          id: string
          plan: string
          plan_renews_at: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          id: string
          plan?: string
          plan_renews_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          plan?: string
          plan_renews_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      api_keys: {
        Row: {
          created_at: string
          id: string
          key_hash: string
          last_used_at: string | null
          name: string
          prefix: string
          revoked_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          key_hash: string
          last_used_at?: string | null
          name?: string
          prefix: string
          revoked_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          key_hash?: string
          last_used_at?: string | null
          name?: string
          prefix?: string
          revoked_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      checks: {
        Row: {
          checked_at: string
          confidence: string | null
          estimate: boolean | null
          http_status: number | null
          id: string
          latency_ms: number | null
          meta: Json | null
          method: string | null
          platform_id: string
          profile_url: string | null
          reason: string | null
          status: string
          username_id: string
        }
        Insert: {
          checked_at?: string
          confidence?: string | null
          estimate?: boolean | null
          http_status?: number | null
          id?: string
          latency_ms?: number | null
          meta?: Json | null
          method?: string | null
          platform_id: string
          profile_url?: string | null
          reason?: string | null
          status: string
          username_id: string
        }
        Update: {
          checked_at?: string
          confidence?: string | null
          estimate?: boolean | null
          http_status?: number | null
          id?: string
          latency_ms?: number | null
          meta?: Json | null
          method?: string | null
          platform_id?: string
          profile_url?: string | null
          reason?: string | null
          status?: string
          username_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "checks_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platform_health"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checks_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platforms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checks_username_id_fkey"
            columns: ["username_id"]
            isOneToOne: false
            referencedRelation: "latest_checks"
            referencedColumns: ["username_id"]
          },
          {
            foreignKeyName: "checks_username_id_fkey"
            columns: ["username_id"]
            isOneToOne: false
            referencedRelation: "usernames"
            referencedColumns: ["id"]
          },
        ]
      }
      platforms: {
        Row: {
          category: string
          created_at: string
          definition_id: string | null
          enabled: boolean
          health_score: number | null
          id: string
          last_selftest_at: string | null
          name: string
          notes: string | null
          nsfw: boolean
          selftest_passed: boolean | null
          signup_url: string | null
          source: string
          updated_at: string
          url_main: string | null
          url_template: string | null
        }
        Insert: {
          category?: string
          created_at?: string
          definition_id?: string | null
          enabled?: boolean
          health_score?: number | null
          id: string
          last_selftest_at?: string | null
          name: string
          notes?: string | null
          nsfw?: boolean
          selftest_passed?: boolean | null
          signup_url?: string | null
          source: string
          updated_at?: string
          url_main?: string | null
          url_template?: string | null
        }
        Update: {
          category?: string
          created_at?: string
          definition_id?: string | null
          enabled?: boolean
          health_score?: number | null
          id?: string
          last_selftest_at?: string | null
          name?: string
          notes?: string | null
          nsfw?: boolean
          selftest_passed?: boolean | null
          signup_url?: string | null
          source?: string
          updated_at?: string
          url_main?: string | null
          url_template?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          display_name: string | null
          fetched_at: string
          followers: number | null
          following: number | null
          id: string
          platform_id: string
          posts: number | null
          profile_url: string | null
          raw: Json
          username_id: string
          verified: boolean | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          display_name?: string | null
          fetched_at?: string
          followers?: number | null
          following?: number | null
          id?: string
          platform_id: string
          posts?: number | null
          profile_url?: string | null
          raw?: Json
          username_id: string
          verified?: boolean | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          display_name?: string | null
          fetched_at?: string
          followers?: number | null
          following?: number | null
          id?: string
          platform_id?: string
          posts?: number | null
          profile_url?: string | null
          raw?: Json
          username_id?: string
          verified?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platform_health"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platforms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_username_id_fkey"
            columns: ["username_id"]
            isOneToOne: false
            referencedRelation: "latest_checks"
            referencedColumns: ["username_id"]
          },
          {
            foreignKeyName: "profiles_username_id_fkey"
            columns: ["username_id"]
            isOneToOne: false
            referencedRelation: "usernames"
            referencedColumns: ["id"]
          },
        ]
      }
      search_history: {
        Row: {
          created_at: string
          handle: string
          id: number
          source: string
          summary: Json
          user_id: string
        }
        Insert: {
          created_at?: string
          handle: string
          id?: never
          source: string
          summary?: Json
          user_id: string
        }
        Update: {
          created_at?: string
          handle?: string
          id?: never
          source?: string
          summary?: Json
          user_id?: string
        }
        Relationships: []
      }
      searches: {
        Row: {
          created_at: string
          duration_ms: number | null
          id: string
          ip_hash: string | null
          platform_count: number | null
          results_summary: Json | null
          source: string
          username: string
          username_id: string | null
        }
        Insert: {
          created_at?: string
          duration_ms?: number | null
          id?: string
          ip_hash?: string | null
          platform_count?: number | null
          results_summary?: Json | null
          source?: string
          username: string
          username_id?: string | null
        }
        Update: {
          created_at?: string
          duration_ms?: number | null
          id?: string
          ip_hash?: string | null
          platform_count?: number | null
          results_summary?: Json | null
          source?: string
          username?: string
          username_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "searches_username_id_fkey"
            columns: ["username_id"]
            isOneToOne: false
            referencedRelation: "latest_checks"
            referencedColumns: ["username_id"]
          },
          {
            foreignKeyName: "searches_username_id_fkey"
            columns: ["username_id"]
            isOneToOne: false
            referencedRelation: "usernames"
            referencedColumns: ["id"]
          },
        ]
      }
      selftest_runs: {
        Row: {
          available_ok: boolean
          definition_id: string | null
          details: Json
          id: number
          passed: boolean | null
          platform_id: string
          run_at: string
          taken_ok: boolean
        }
        Insert: {
          available_ok: boolean
          definition_id?: string | null
          details?: Json
          id?: never
          passed?: boolean | null
          platform_id: string
          run_at?: string
          taken_ok: boolean
        }
        Update: {
          available_ok?: boolean
          definition_id?: string | null
          details?: Json
          id?: never
          passed?: boolean | null
          platform_id?: string
          run_at?: string
          taken_ok?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "selftest_runs_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platform_health"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "selftest_runs_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platforms"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_counters: {
        Row: {
          count: number
          day: string
          metric: string
          subject: string
          updated_at: string
        }
        Insert: {
          count?: number
          day?: string
          metric: string
          subject: string
          updated_at?: string
        }
        Update: {
          count?: number
          day?: string
          metric?: string
          subject?: string
          updated_at?: string
        }
        Relationships: []
      }
      usernames: {
        Row: {
          first_seen: string
          handle: string
          id: string
          last_checked: string | null
        }
        Insert: {
          first_seen?: string
          handle: string
          id?: string
          last_checked?: string | null
        }
        Update: {
          first_seen?: string
          handle?: string
          id?: string
          last_checked?: string | null
        }
        Relationships: []
      }
      watchlist: {
        Row: {
          created_at: string
          freed_at: string | null
          handle: string
          id: string
          last_checked_at: string | null
          last_status: string | null
          notified_at: string | null
          platform_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          freed_at?: string | null
          handle: string
          id?: string
          last_checked_at?: string | null
          last_status?: string | null
          notified_at?: string | null
          platform_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          freed_at?: string | null
          handle?: string
          id?: string
          last_checked_at?: string | null
          last_status?: string | null
          notified_at?: string | null
          platform_id?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      latest_checks: {
        Row: {
          category: string | null
          checked_at: string | null
          confidence: string | null
          estimate: boolean | null
          handle: string | null
          http_status: number | null
          id: string | null
          latency_ms: number | null
          meta: Json | null
          method: string | null
          platform_id: string | null
          platform_name: string | null
          profile_url: string | null
          reason: string | null
          status: string | null
          username_id: string | null
        }
        Relationships: [
          {
            foreignKeyName: "checks_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platform_health"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checks_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platforms"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_health: {
        Row: {
          available_24h: number | null
          avg_latency_ms_24h: number | null
          category: string | null
          checks_24h: number | null
          enabled: boolean | null
          health_score: number | null
          id: string | null
          last_checked_at: string | null
          last_selftest_at: string | null
          name: string | null
          notes: string | null
          nsfw: boolean | null
          selftest_passed: boolean | null
          source: string | null
          taken_24h: number | null
          unknown_24h: number | null
          unknown_rate_24h: number | null
          url_main: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      consume_usage: {
        Args: {
          p_amount?: number
          p_limit: number
          p_metric: string
          p_subject: string
        }
        Returns: {
          allowed: boolean
          used: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
